alias zshconfig="atom ~/.zshrc"
alias ohmyzsh="atom ~/.oh-my-zsh"
alias disable-web-security="open -na Google\ Chrome --args --user-data-dir=/tmp/temporary-chrome-profile-dir --disable-web-security --disable-site-isolation-trials"
alias slow-internet-npm-i="npm install --prefer-offline --no-audit --ignore-scripts"
alias etc-hosts-file="atom /etc/hosts"
alias hyper-config="atom ~/.hyper.js"
